spring:
  datasource:
    url: jdbc:mysql://localhost:3306/produce_management?serverTimezone=GMT%2B8
    username: root
    password: sql2008
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081